### ISSUE TITLE
Technologies to use

### ISSUE THREAD

**Issue by slopez1** [AmplifyForPeople/amplify-service#2]
Para la solución se ha de definir claramente que tecnologías se utilizaran para el desarrollo de la misma.

Se requiere definir:
Los idles que se usaran.
Las versiones de las tecnologías que se utilizaran.
Así como servicios intermedios que se utilizaran.

Se espera obtener un documento donde conste toda esta información.

**Comment by vrnvu** [comment]
https://github.com/AmplifyForPeople/amplify-service/wiki/Technologies
