### ISSUE TITLE
App architecture

### ISSUE THREAD

**Issue by slopez1** [AmplifyForPeople/amplify-service#3]
Se ha de definir claramente la totalidad de la arquitectura que se esperara utilizar en la solución.

Como validación:
Se ha de obtener un diagrama donde conste toda la arquitectura prevista para la aplicación.

**Comment by vrnvu** [comment]
@ffriz22 Is this the final version?
![architecture](https://user-images.githubusercontent.com/12988581/47614405-c126c980-da9f-11e8-9ef2-f51869e3d8fd.png)

**Comment by ffriz22** [comment]
If the whole team sees it right, yeah 😄
