### ISSUE TITLE
Taking requirements

### ISSUE THREAD

**Issue by slopez1** [AmplifyForPeople/amplify-service#4]
Se han de detectar la mayoría (ha ser posible todos) los requerimientos funcionales de la solución.

Para la validación esperara la obtención de un documento donde consten todos los requerimientos funcionales identificados.

**Comment by vrnvu** [comment]
Requerimientos desde el punto de vista del usuario.
Requerimientos desde el punto de vista del cliente.

@slopez1 A partir de los requerimientos podrás crear los casos de uso y backlog.

**Comment by slopez1** [comment]
Sí, me estare a la espera de @ffriz22 y @KevinGarMill

**Comment by ffriz22** [comment]
Requirements do it, I add the functional requirements of the Android App (Users) and  @KevinGarMill  add the functional requirements of the Web Application (Client) 👍.
