### ISSUE TITLE
Detection of agents

### ISSUE THREAD

**Issue by slopez1** [AmplifyForPeople/amplify-service#6]
Se requiere que se especifiquen claramente todos los agentes que conformen la solución.

Se entiende como agente toda entidad independiente, con suficiente identidad , de terceros o no, que de alguna forma estén involucrados en la solución.

Para la validación se espera obtener un documento donde consten todos estos agentes con una breve descripción de como afectan en la solución.

**Comment by vrnvu** [comment]
@slopez1 https://github.com/AmplifyForPeople/amplify-service/wiki/Agents
