### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by slopez1** [AmplifyForPeople/amplify-service#7]
Se requiere un glosario en el cual consten todas las palabras que puedan causar confusión entre los miembros del grupo.

Se espera obtener un documento "El glosario", en el cual se vaya apuntando las palabras que puedan causar confusión en el equipo de desarrollo.

**Comment by vrnvu** [comment]
Wiki reference: https://github.com/AmplifyForPeople/amplify-service/wiki/Glossary

As a global issue, I'd suggest @ffriz22 and @KevinGarMill to add their modifications of the model to the glossary for quick reference.

**Comment by ffriz22** [comment]
Yeah, i added the term "Amplify Sites": Establishments with Amplify technology
