### ISSUE TITLE
State of art of recommendations.

### ISSUE THREAD

**Issue by slopez1** [AmplifyForPeople/amplify-service#90]

**Comment by vrnvu** [comment]
**Naive approach: recommend most popular and well-rated establishments**
-  Get top 10 better rated establishments near
- Compute a ration between rating value and popularity
- Top establishments sorted by the relation average rating - number of times rated
- Get top popular profiles with average rating and gender information

**Comment by vrnvu** [comment]
**Collaborative filtering**
- Generate top 10 establishment recommendation for each user
- Generate top 10 near establishment recommendation for each user

**Comment by vrnvu** [comment]
**MQTT/or similar over HTTP in Android device**
- MQTT is data centric whereas HTTP is document-centric. HTTP is request-response protocol for client-server computing and not always optimized for mobile devices. Main solid benefits of MQTT in these terms are lightweightness (MQTT transfers data as a byte array) and publish/subscribe model, which makes it perfect for resource-constrained devices and help to save battery.

- Besides, publish/subscribe model provides clients with independent existence from one another and enhance the reliability of the whole system. When one client is out of order the whole system can keep on working properly.

- According to measurements in 3G networks, throughput of MQTT is 93 times faster than HTTP’s.

- Besides, in comparison to HTTP, MQTT Protocol ensures high delivery guarantees. There are 3 levels of Quality of Services:

- at most once: guarantees a best effort delivery.

- at least once: guaranteed that a message will be delivered at least once. But the message can also be delivered more than once.

- exactly once: guarantees that each message is received only once by the counterpart

- MQTT Protocol is easy of use. It is essential when response time, throughput, lower battery and bandwidth usage are on the first place for future solutions. It’s also perfect in case of intermittent connectivity.
